### ISSUE TITLE
Usage info

### ISSUE THREAD

**Issue by awrelll** [danielchalef/pyethrecoverv3#1]
Can you please add some documentation on how to use this tool ?
After all attempts I get no result . How does the successfully cracking look like ?

**Comment by danielchalef** [comment]
Please take a look at the documentation for [pyethrecover](https://github.com/burjorjee/pyethrecover) and [How to apply pyethrecover.py on v3 .json/transfor v3 .json to .v1](https://ethereum.stackexchange.com/questions/6845/how-to-apply-pyethrecover-py-on-v3-json-transfor-v3-json-to-v1/12249#12249)

**Comment by anywalletrecovery** [comment]
I have machine for wallet recovery and can recover wallet password
Telegram: @walletrecover
